### ISSUE TITLE
Pass argument to `extract` as reference

### ISSUE THREAD

**Issue by DTharun** [IITH-Compilers/P4LLVM#3]
`  %3 = load %struct.Headers, %struct.Headers* %h
  %4 = getelementptr %struct.Headers, %struct.Headers* %h, i32 0, i32 1
  %5 = getelementptr %struct.hu, %struct.hu* %4, i32 0, i32 0
  %6 = load %struct.hdr, %struct.hdr* %5
  call void @extract(%struct.hdr %6)`

In the above code snipped, the argument to extract function call is passed by value. I think it should be by reference so that any expression following `extract` will think that the argument might not be the same as the original.

What do you think?

**Comment by svkeerthy** [comment]
Fixed by passing all extern functions' out params as reference
