### ISSUE TITLE
Implementaiton of `verify` function

### ISSUE THREAD

**Issue by DTharun** [IITH-Compilers/P4LLVM#5]
`verify` function can be implemented in backend only after handling `errors` in the frontend.
Mark this fixed when `errors` are handled, I can take up verify.

`    state start {
        verify(meta.x == 0, error.NewError);
        verify(true, error.NoError);
        error e = error.NoError;
        verify(true, e);
        transition accept;
    }
}`
llvm_unreachable in backend.cpp:getCorrespondingType()

**Comment by svkeerthy** [comment]
Fixed by handling error type
